# Single configuration for both development and production
services:
  backend:
    build: .
    container_name: receipts-api
    restart: unless-stopped
    ports:
      - "8001:8000"  # FastAPI backend (matching existing port)
    environment:
      - ENVIRONMENT=production
      # Database configuration
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SPARKDB_USER=${SPARKDB_USER}
      - SPARKDB_PASSWORD=${SPARKDB_PASSWORD}
      - PG_DB_PORT=${DB_PORT}  # Your code uses PG_DB_PORT, mapping from DB_PORT
      # App secrets
      - APP_KEY=${APP_KEY}
      - JWT_KEY=${JWT_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMAIL_WHITELIST=${EMAIL_WHITELIST}
      - TRAINING_DB_NAME=${TRAINING_DB_NAME}
    # Remove volume mounts for production deployment
    # volumes:
    #   - .:/app
    #   - /app/__pycache__
    # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - receipts-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: receipts
    restart: unless-stopped
    ports:
      - "4400:4400"  # Angular production server
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - receipts-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.receipts.rule=Host(`receipts.sparktobloom.com`)"
      - "traefik.http.routers.receipts.entrypoints=web"
      - "traefik.http.services.receipts.loadbalancer.server.port=4400"
      # API routing
      - "traefik.http.routers.receipts-api.rule=Host(`receipts.sparktobloom.com`) && PathPrefix(`/auth`, `/receipts`)"
      - "traefik.http.routers.receipts-api.entrypoints=web"
      - "traefik.http.routers.receipts-api.service=receipts-api"
      - "traefik.http.services.receipts-api.loadbalancer.server.port=8001"
      # Trust Cloudflare's forwarded headers
      - "traefik.http.middlewares.cloudflare-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.receipts.middlewares=cloudflare-headers"
      - "traefik.http.routers.receipts-api.middlewares=cloudflare-headers"

networks:
  receipts-network:
    driver: bridge