# Simpler configuration - route everything to Streamlit
services:
  receipts:
    build: .
    container_name: receipts
    restart: unless-stopped
    environment:
      - ENVIRONMENT=development
      - API_BASE_URL=http://localhost:8001
      # Database configuration
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SPARKDB_USER=${SPARKDB_USER}
      - SPARKDB_PASSWORD=${SPARKDB_PASSWORD}
      - PG_DB_PORT=${DB_PORT}  # Your code uses PG_DB_PORT, mapping from DB_PORT
      # App secrets
      - APP_KEY=${APP_KEY}
      - JWT_KEY=${JWT_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMAIL_WHITELIST=${EMAIL_WHITELIST}
      - TRAINING_DB_NAME=${TRAINING_DB_NAME}
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.receipts.rule=Host(`receipts.sparktobloom.com`)"
      - "traefik.http.routers.receipts.entrypoints=web"
      - "traefik.http.services.receipts.loadbalancer.server.port=8501"
      # Trust Cloudflare's forwarded headers
      - "traefik.http.middlewares.cloudflare-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.receipts.middlewares=cloudflare-headers"
    
    networks:
      - traefik-global

networks:
  traefik-global:
    external: true