# Local Development Configuration for Receipts
# Usage: docker-compose up
services:
  receipts:
    build: .
    container_name: receipts
    restart: unless-stopped
    environment:
      - ENVIRONMENT=development
    #ports:
      #- "8000:8000"  # Direct port mapping for local development

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.receipts.rule=Host(`receipts.sparktobloom.com`)"
      - "traefik.http.routers.receipts.entrypoints=web"
      # No TLS configuration - Cloudflare handles SSL termination
      #- "traefik.http.services.receipts.loadbalancer.server.port=8000"
      # Trust Cloudflare's forwarded headers
      - "traefik.http.middlewares.cloudflare-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.receipts.middlewares=cloudflare-headers"
    
    networks:
      - traefik-global

networks:
  traefik-global:
    external: true